// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASP.NET_Core_Web_API_with_Minimal_APIs_and_OpenAPI_support.Models;

public partial class Course
{
    public int CourseId { get; set; }

    public string Title { get; set; }

    public int Credits { get; set; }

    public int DepartmentId { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<Enrollment> Enrollment { get; } = new List<Enrollment>();

    public virtual ICollection<Person> Instructor { get; } = new List<Person>();
}