// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASP.NET_Core_Web_API_with_Minimal_APIs_and_OpenAPI_support.Models;

public partial class OfficeAssignment
{
    public int InstructorId { get; set; }

    public string Location { get; set; }

    public virtual Person Instructor { get; set; }
}