// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASP.NET_Core_Web_API_with_Minimal_APIs_and_OpenAPI_support.Models;

public partial class Person
{
    public int Id { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public DateTime? HireDate { get; set; }

    public DateTime? EnrollmentDate { get; set; }

    public string Discriminator { get; set; }

    public virtual ICollection<Department> Department { get; } = new List<Department>();

    public virtual ICollection<Enrollment> Enrollment { get; } = new List<Enrollment>();

    public virtual OfficeAssignment OfficeAssignment { get; set; }

    public virtual ICollection<Course> Course { get; } = new List<Course>();
}